"""initial schema

Revision ID: e6288eb976ce
Revises: 
Create Date: 2026-04-07 19:55:00.299701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6288eb976ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('anomaly_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('trigger_data', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('density', sa.Float(), nullable=True),
    sa.Column('community_count', sa.Integer(), nullable=True),
    sa.Column('centrality_metrics', sa.JSON(), nullable=True),
    sa.Column('metadata_tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_snapshots_timestamp'), ['timestamp'], unique=False)

    op.create_table('identity_markers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('repository_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('relational_edges',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relational_edges', schema=None) as batch_op:
        batch_op.create_index('ix_edge_source_id', ['source_id'], unique=False)
        batch_op.create_index('ix_edge_source_target_type', ['source_id', 'target_id', 'relationship_type'], unique=False)
        batch_op.create_index('ix_edge_target_id', ['target_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('proficiency_level', sa.Float(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('milestones',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestones')
    op.drop_table('skills')
    with op.batch_alter_table('relational_edges', schema=None) as batch_op:
        batch_op.drop_index('ix_edge_target_id')
        batch_op.drop_index('ix_edge_source_target_type')
        batch_op.drop_index('ix_edge_source_id')

    op.drop_table('relational_edges')
    op.drop_table('projects')
    op.drop_table('identity_markers')
    with op.batch_alter_table('graph_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_snapshots_timestamp'))

    op.drop_table('graph_snapshots')
    op.drop_table('anomaly_events')
    # ### end Alembic commands ###
